### ISSUE TITLE
[BUG]: WRONG DOCUMENTATION PATH

### ISSUE THREAD

**Issue by obrucheoghene** [fonoster/goodtok#24]
### What happened?

Clicking on DOCUMENTATION on the hero section of the landing page opens the goodtok github repo instead of the docs page in 
https://goodtok.io/docs/welcome/

<img width="1288" alt="github " src="https://github.com/fonoster/goodtok/assets/111436934/a9956631-c546-4cc2-aff0-8157241bb672">

### Steps to reproduce

1. Visit https://goodtok.io/
2. Find and click on 'DOCUMENTATION' on the hero section

### Expected behavior

The documentation URL should be https://goodtok.io/docs/welcome/

**Comment by obrucheoghene** [comment]
Should I fix this?

**Comment by psanders** [comment]
@obrucheoghene

Yes! Please submit a PR for this :)

**Comment by obrucheoghene** [comment]
I have submitted a PR for it.

**Comment by psanders** [comment]
Fixed by https://github.com/fonoster/goodtok/pull/25
