### ISSUE TITLE
[BUG]: Installation Issue

### ISSUE THREAD

**Issue by voipiran** [fonoster/goodtok#41]
### What happened?

Hi, I am trying install goodtok on ubuntu after installing docker via you installation giude.
after this command:
docker compose up -d

i have git this error:

root@goodtok:~/goodtok# docker compose up -d
WARN[0000] The "EMAIL_TEMPLATES_DIR" variable is not set. Defaulting to a blank string.
WARN[0000] /root/goodtok/compose.yaml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
[+] Running 1/1
 ✘ apiserver Error toomanyrequests: Too Many Requests (HAP429).                                                                           1.9s
Error response from daemon: toomanyrequests: Too Many Requests (HAP429).
root@goodtok:~/goodtok# ^C
root@goodtok:~/goodtok#

### Steps to reproduce

1. run: docker compose up -d

### Expected behavior

root@goodtok:~/goodtok# docker compose up -d
WARN[0000] The "EMAIL_TEMPLATES_DIR" variable is not set. Defaulting to a blank string.
WARN[0000] /root/goodtok/compose.yaml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
[+] Running 1/1
 ✘ apiserver Error toomanyrequests: Too Many Requests (HAP429).                                                                           1.9s
Error response from daemon: toomanyrequests: Too Many Requests (HAP429).

**Comment by psanders** [comment]
@voipiran, is there any chance you might be hitting a rate limit by Docker Hub?

**Comment by psanders** [comment]
@voipiran I'm closing this, but if you are still facing the issue, let me know.
